# JVM args
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric / Minecraft 26.1.2
# Перепроверять на https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod
mod_version=1.1.0+mc26.1.2
maven_group=dev.fix85
archives_base_name=autovault

# Fabric API
fabric_api_version=0.149.1+26.1.2
